### ISSUE TITLE
Optionally Generate TestNG Classes

### ISSUE THREAD

**Issue by opticyclic** [mernst/randoop#52] opened 2015-06-07 06:39 UTC
It would be good if Randoop could generate TestNG tests as well as JUnit.

**Comment by mernst** [comment] 2015-07-13 09:49
That sounds great.  It isn't too much work because it's just a matter of formatting.  Please feel free to implement this and submit a pull request.  I'll close the issue for now, but we would be glad to incorporate such an improvement in Randoop.

**Closed by mernst** 2015-07-13 09:49 UTC

**Comment by nathanila** [comment] 2019-01-17 16:58
Why was this issue closed?  What the feature implemented?

**Comment by mernst** [comment] 2019-01-18 22:50
The issue is closed because we don't use the issue tracker as an exhaustive list of potential features.  (Otherwise it would contain hundreds or thousands of feature requests, and features would swamp bug reports.)

This is reflected in the second comment in the thread, which encourages a pull request and closes the issue.

**Comment by nathanila** [comment] 2019-01-20 15:39
How do you track feature requests?  Other GitHub groups label feature requests with "feature".  When looking for bugs, they exclude issues labeled with "feature".

**Comment by nathanila** [comment] 2019-01-20 15:40
By closing the issue, you send a strong message that you do not care to ever implement the feature.  This will turn your user base away.
